spring:
  application:
    name: CRUD-expense-service

  datasource:
    url: jdbc:mysql://localhost:3306/crud_expense_db?serverTimezone=Asia/Kolkata
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      ddl-show: true

server:
  port: 8082

user:
  service:
    url: http://localhost:8081
